### ISSUE TITLE
Error compile in IOS

### ISSUE THREAD

**Issue by obravoInserious** [arsenal942/Cordova-Network-Manager#2]
### Issue type
Bug

### Description
Hello, first thank you for your work. 
When compiling for IOS with `ionic cordova run ios`, the compilation returns an error of the plugin:

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NEHotspotConfigurationManager", referenced from:
      objc-class-ref in cordovaNetworkManager.o
  "_OBJC_CLASS_$_NEHotspotConfiguration", referenced from:
      objc-class-ref in cordovaNetworkManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

ionic -v -> 3.19.0
cordova -v -> 7.1.0

Another question I have is: how do I import the plugin into ionic 3 with typescript?
Thank you very much for your help and your great work.

**Comment by arsenal942** [comment]
Hi @obravoInserious 

The problem is that the iOS11 NEHotspot config doesn't let you run in a simulator and requires you to have an actual device connected to the computer when you are building. It's an absolute pain and I received the same error as you. It took me about 6 hours of running in circles before I found out what was the problem.

Let me know if attaching an actual device works.


In-regards to you ionic 3 question, I'm not quite sure. You might need to do a quick Google search. I'll have a look around and see if I can find an answer for you.

**Comment by arsenal942** [comment]
@obravoInserious Did you get it working?

**Comment by arsenal942** [comment]
I will close this issue since I haven't heard back. If it continues to persist, create a new one.
