### ISSUE TITLE
Enable WiFi when calling funcs that require WiFi enabled

### ISSUE THREAD

**Issue by tripflex** [arsenal942/Cordova-Network-Manager#5]
Any reason for not having code in the functions/methods that require WiFi to be enabled, to automatically enable it?

I get that it's possible to do, but right now, I have to first check if WiFi is not enabled, and then Enable it, and then I can call something like `addNetwork` ... why not just have code in the `addNetwork` and other functions that require wifi to be enabled, to automatically enable it if it's not already enabled?

**Comment by arsenal942** [comment]
No particular reason - I just never got around to writing the function. I will add it in the next release (2.2.0) as it's pretty straight forward.

**Comment by arsenal942** [comment]
There is already a method called 'setWifiEnabled' that will let you enable or disable the currently connected network.

I will change this method so that you have to give it an SSID that you want to enable/disable accordingly. If you don't give it an SSID, it will just enable/disable the currently connected network.

Going back to your main point though about "Why not just having X function do XYZ" - I'm all about modularity when it comes to methods. I prefer to have lots of little functions that perform one specific task so you're able to chain together multiple methods to do what you want, rather than one big function that does 3. It makes it much easier to re-write functions in the future without breaking a whole lot of code.

**Comment by tripflex** [comment]
Hey just to let you know, I just went ahead and created a fork of the WifiWizard and named it WifiWizard2 (since you were saying that most of this was your project specific code), to allow others to contribute to and keep it as a general plugin in a sense:
https://github.com/tripflex/WifiWizard2

I do have some changes in my fork of this repo though I can submit as a PR if you want?

**Comment by arsenal942** [comment]
@tripflex Anything that you think will benefit the plugin, feel free to commit.

This plugin is still 99% general and I created it because I needed to be able to programatically connect iOS11+ devices to a WiFi network. The original WifiWizard code is pretty meh and I am in the middle of a complete re-write of it.

**Comment by arsenal942** [comment]
As I stated above, I am about modularity when writing code and don't like having functions that chain onto other functions. This can cause unexpected consequences and I would rather functions be user triggered than application/system triggered.

In a future rewrite, I may add these 'chain' functions which perform multiple functions however for now, I don't plan to.
